apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: dpeckett/airgapify
    githubRelease:
      slug: dpeckett/airgapify
      tag: v0.6.2
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: dpeckett/apimachinery
    githubRelease:
      slug: dpeckett/apimachinery
      tag: git20240904.c1bfe04
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: dpeckett/aptify
    githubRelease:
      slug: dpeckett/aptify
      tag: v0.8.0
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: dpeckett/archivefs
    githubRelease:
      slug: dpeckett/archivefs
      tag: v0.11.1
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: dpeckett/deb822
    githubRelease:
      slug: dpeckett/deb822
      tag: v0.5.3
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: dpeckett/fsutil
    githubRelease:
      slug: dpeckett/fsutil
      tag: git20240902.85aeae2
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: dpeckett/telemetry
    githubRelease:
      slug: dpeckett/telemetry
      tag: v0.1.2
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: dpeckett/uncompr
    githubRelease:
      slug: dpeckett/uncompr
      tag: v0.5.0
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: dpeckett/vt100
    githubRelease:
      slug: dpeckett/vt100
      tag: git20240719.6f69db9
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: immutos/debco
    githubRelease:
      slug: immutos/debco
      tag: v0.17.1
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: immutos/matchstick
    githubRelease:
      slug: immutos/matchstick
      tag: v0.4.0
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"
  - path: immutos/oci2erofs
    githubRelease:
      slug: immutos/oci2erofs
      tag: v0.4.0
      disableAutoChecksumValidation: true
      assetNames:
      - "*.deb"